# Generated by Django 6.0.3 on 2026-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Silo')),
                ('capacity', models.FloatField(verbose_name='Capacidade Máxima (Toneladas)')),
                ('current_quantity', models.FloatField(default=0, verbose_name='Quantidade Atual (Toneladas)')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Produto')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('desativado', 'Desativado')], default='ativo', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Silo',
                'verbose_name_plural': 'Silos',
                'ordering': ['name'],
            },
        ),
    ]
