# Generated by Django 6.0.3 on 2026-03-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_silo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'verbose_name': 'Configuração de Sensor', 'verbose_name_plural': 'Configurações de Sensores'},
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição/Localização'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.silo'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID do Sensor (Físico)'),
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.IntegerField(verbose_name='ID Local do Gateway')),
                ('temperature', models.FloatField(verbose_name='Temperatura (°C)')),
                ('humidity', models.FloatField(verbose_name='Umidade (%)')),
                ('timestamp', models.DateTimeField(verbose_name='Data/Hora da Coleta (ISO)')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Recebimento')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='api.sensordata')),
            ],
            options={
                'verbose_name': 'Telemetria',
                'verbose_name_plural': 'Telemetrias',
                'ordering': ['-timestamp'],
            },
        ),
    ]
