# Generated by Django 6.0.3 on 2026-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sensordata_options_remove_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('falha', 'Falha de Leitura'), ('desativado', 'Desativado')], default='ativo', max_length=20, verbose_name='Status de Operação'),
        ),
    ]
