# Generated by Django 6.0.3 on 2026-03-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sensordata_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetry',
            old_name='temperature',
            new_name='temperatura',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='humidity',
            new_name='umidade',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='id_local',
        ),
    ]
