# Generated by Django 6.0.3 on 2026-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_temperature_telemetry_temperatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silo',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
