# Generated by Django 6.0.3 on 2026-04-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_silo_observations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Fazenda/Armazém')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização/Cidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observações da Unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Fazenda/Armazém',
                'verbose_name_plural': 'Fazendas/Armazéns',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='silo',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silos', to='api.farm', verbose_name='Fazenda/Armazém'),
        ),
    ]
