# Generated by Django 6.0.3 on 2026-04-17 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_farm_silo_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL, verbose_name='Dono/Usuário'),
            preserve_default=False,
        ),
    ]
