# Generated by Django 6.0.3 on 2026-04-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_farm_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True, verbose_name='Número do Lote')),
                ('cultura', models.CharField(max_length=100, verbose_name='Cultura (ex: Milho, Soja)')),
                ('variedade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedade')),
                ('safra', models.CharField(max_length=20, verbose_name='Safra')),
                ('peso_inicial', models.FloatField(verbose_name='Peso Inicial (kg)')),
                ('umidade_inicial', models.FloatField(verbose_name='Umidade Inicial (%)')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('peso_final', models.FloatField(blank=True, null=True, verbose_name='Peso Final (kg)')),
                ('umidade_final', models.FloatField(blank=True, null=True, verbose_name='Umidade Final (%)')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('secando', 'Em Secagem'), ('finalizado', 'Finalizado'), ('despachado', 'Despachado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.farm', verbose_name='Fazenda/Unidade')),
                ('silo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='api.silo', verbose_name='Silo de Destino')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
