# Generated by Django 6.0.3 on 2026-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_combustivel', models.FloatField(default=0, verbose_name='Preço Combustível (R$/unid)')),
                ('preco_kwh', models.FloatField(default=0, verbose_name='Preço Energia (R$/kWh)')),
                ('preco_mao_de_obra_hora', models.FloatField(default=0, verbose_name='Preço Mão de Obra (R$/hora)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='consumo_combustivel',
            field=models.FloatField(default=0, verbose_name='Consumo de Combustível (unid)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='consumo_energia',
            field=models.FloatField(default=0, verbose_name='Consumo de Energia (kWh)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='horas_operacao',
            field=models.FloatField(default=0, verbose_name='Horas de Operação'),
        ),
        migrations.AddField(
            model_name='lote',
            name='mao_de_obra_quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade de Operadores'),
        ),
        migrations.AddField(
            model_name='silo',
            name='custo_inicial',
            field=models.FloatField(default=0, verbose_name='Custo Inicial (Ci)'),
        ),
        migrations.AddField(
            model_name='silo',
            name='valor_sucata',
            field=models.FloatField(default=0, verbose_name='Valor de Sucata (Cf)'),
        ),
        migrations.AddField(
            model_name='silo',
            name='vida_util_anos',
            field=models.IntegerField(default=20, verbose_name='Vida Útil em Anos (n)'),
        ),
    ]
