# Generated by Django 6.0.3 on 2026-04-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_silo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silo',
            name='status',
            field=models.CharField(choices=[('livre', 'Disponível para uso'), ('ocupado', 'Já contém um lote'), ('manutencao', 'Em manutenção técnica'), ('desativado', 'Inativo')], default='livre', max_length=20, verbose_name='Status'),
        ),
    ]
