# Generated by Django 6.0.3 on 2026-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_silo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silo',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Manutenção'), ('desativado', 'Desativado')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
    ]
