# Generated by Django 6.0.3 on 2026-04-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_silo_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='consumo_combustivel',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='consumo_energia',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='horas_operacao',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='mao_de_obra_quantidade',
        ),
        migrations.RemoveField(
            model_name='silo',
            name='custo_inicial',
        ),
        migrations.RemoveField(
            model_name='silo',
            name='valor_sucata',
        ),
        migrations.RemoveField(
            model_name='silo',
            name='vida_util_anos',
        ),
    ]
