# Generated by Django 6.0.3 on 2026-05-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_globalsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silo',
            name='product_type',
        ),
        migrations.CreateModel(
            name='Secador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Secador')),
                ('tipo', models.CharField(choices=[('Coluna', 'Coluna'), ('Cascata', 'Cascata'), ('Fluxo Contínuo', 'Fluxo Contínuo'), ('Batelada', 'Batelada')], default='Coluna', max_length=20, verbose_name='Tipo')),
                ('capacidade', models.FloatField(verbose_name='Capacidade (t/h)')),
                ('fonte_calor', models.CharField(choices=[('Lenha', 'Lenha'), ('Gás GLP', 'Gás GLP'), ('Biomassa', 'Biomassa'), ('Elétrico', 'Elétrico')], default='Lenha', max_length=20, verbose_name='Fonte de Calor')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Manutenção', 'Manutenção'), ('Inativo', 'Inativo')], default='Ativo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secadores', to='api.farm', verbose_name='Fazenda/Unidade')),
            ],
            options={
                'verbose_name': 'Secador',
                'verbose_name_plural': 'Secadores',
                'ordering': ['nome'],
            },
        ),
    ]
