# Generated by Django 6.0.3 on 2026-05-06 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_silo_product_type_secador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('umidade_alvo', models.FloatField(verbose_name='Umidade Alvo (%)')),
                ('temperatura_trabalho', models.FloatField(verbose_name='Temperatura de Trabalho (°C)')),
                ('status', models.CharField(choices=[('Executando', 'Executando'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Executando', max_length=20, verbose_name='Status')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador Responsável')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='api.lote', verbose_name='Lote')),
                ('secador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='api.secador', verbose_name='Secador')),
            ],
            options={
                'verbose_name': 'Processo de Secagem',
                'verbose_name_plural': 'Processos de Secagem',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
