# Generated by Django 6.0.3 on 2026-05-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_processo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Processo Operacional', 'verbose_name_plural': 'Processos Operacionais'},
        ),
        migrations.AddField(
            model_name='processo',
            name='data_liberacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Liberação'),
        ),
        migrations.AddField(
            model_name='processo',
            name='dosagem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dosagem'),
        ),
        migrations.AddField(
            model_name='processo',
            name='produto_quimico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto Químico'),
        ),
        migrations.AddField(
            model_name='processo',
            name='silo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_destino', to='api.silo', verbose_name='Silo de Destino'),
        ),
        migrations.AddField(
            model_name='processo',
            name='silo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_origem', to='api.silo', verbose_name='Silo de Origem'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo_processo',
            field=models.CharField(choices=[('Secagem', 'Secagem'), ('Aeração', 'Aeração'), ('Transilagem', 'Transilagem'), ('Expurgo', 'Expurgo'), ('Expedição', 'Expedição')], default='Secagem', max_length=20, verbose_name='Tipo de Atividade'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='api.lote', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='secador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='api.secador', verbose_name='Secador'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='temperatura_trabalho',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura de Trabalho (°C)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='umidade_alvo',
            field=models.FloatField(blank=True, null=True, verbose_name='Umidade Alvo (%)'),
        ),
    ]
