# Generated by Django 6.0.3 on 2026-05-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_processo_options_processo_data_liberacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='data_liberacao',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='dosagem',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='produto_quimico',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='secador',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='silo_destino',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='silo_origem',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='temperatura_trabalho',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='umidade_alvo',
        ),
    ]
