# Generated by Django 6.0.3 on 2026-05-06 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_processo_data_liberacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador Responsável'),
        ),
    ]
