# Generated by Django 6.0.3 on 2026-05-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_processo_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('finalizado', 'Finalizado'), ('despachado', 'Despachado'), ('Secagem', 'Em Secagem'), ('Aeração', 'Em Aeração'), ('Transilagem', 'Em Transilagem'), ('Expurgo', 'Em Expurgo'), ('Expedição', 'Em Expedição')], default='aguardando', max_length=20, verbose_name='Status'),
        ),
    ]
