# Generated by Django 6.0.3 on 2026-05-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('finalizado', 'Finalizado'), ('despachado', 'Despachado'), ('Secagem (Executando)', 'Secagem (Executando)'), ('Secagem (Pausado)', 'Secagem (Pausado)'), ('Aeração (Executando)', 'Aeração (Executando)'), ('Aeração (Pausado)', 'Aeração (Pausado)'), ('Transilagem (Executando)', 'Transilagem (Executando)'), ('Expurgo (Executando)', 'Expurgo (Executando)'), ('Expedição (Executando)', 'Expedição (Executando)')], default='aguardando', max_length=50, verbose_name='Status'),
        ),
    ]
