# Generated by Django 6.0.3 on 2026-05-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('finalizado', 'Finalizado'), ('despachado', 'Despachado'), ('Secagem (Iniciada)', 'Secagem (Iniciada)'), ('Secagem (Pausada)', 'Secagem (Pausada)'), ('Secagem (Finalizada)', 'Secagem (Finalizada)'), ('Secagem (Cancelada)', 'Secagem (Cancelada)'), ('Aeração (Iniciada)', 'Aeração (Iniciada)'), ('Aeração (Pausada)', 'Aeração (Pausada)'), ('Aeração (Finalizada)', 'Aeração (Finalizada)'), ('Aeração (Cancelada)', 'Aeração (Cancelada)')], default='aguardando', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('Iniciada', 'Iniciada'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Iniciada', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_processo',
            field=models.CharField(choices=[('Secagem', 'Secagem'), ('Aeração', 'Aeração')], default='Secagem', max_length=20, verbose_name='Tipo de Atividade'),
        ),
    ]
