# Generated by Django 6.0.3 on 2026-05-08 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_lote_status_alter_processo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.farm'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='secador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.secador'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='tipo',
            field=models.CharField(default='sensor_temperatura', max_length=100, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='dados_extras',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dados Extras (JSON)'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='temperatura',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='umidade',
            field=models.FloatField(blank=True, null=True, verbose_name='Umidade (%)'),
        ),
    ]
