# Generated by Django 6.0.3 on 2026-05-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_sensordata_farm_sensordata_secador_sensordata_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do Lote'),
        ),
    ]
