# Generated by Django 6.0.3 on 2026-05-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='secador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='api.secador', verbose_name='Secador'),
        ),
    ]
