# Generated by Django 6.0.3 on 2026-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_processo_secador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='tipo_processo',
            field=models.CharField(choices=[('Secagem', 'Secagem'), ('Aeração', 'Aeração'), ('Expurgo', 'Expurgo'), ('Transilagem', 'Transilagem'), ('Resfriamento', 'Resfriamento')], default='Secagem', max_length=20, verbose_name='Tipo de Atividade'),
        ),
    ]
