# Generated by Django 6.0.3 on 2026-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_processo_tipo_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='tipo_processo',
            field=models.CharField(choices=[('Secagem', 'Secagem'), ('Resfriamento', 'Resfriamento'), ('Armazenamento', 'Armazenamento')], default='Secagem', max_length=20, verbose_name='Tipo de Atividade'),
        ),
    ]
