# Generated by Django 6.0.3 on 2026-05-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_processo_tipo_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='api.silo', verbose_name='Silo'),
        ),
    ]
