# Generated by Django 6.0.3 on 2026-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_processo_silo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secador',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Em Uso', 'Em Uso'), ('Em Manutenção', 'Em Manutenção'), ('Desativado', 'Desativado')], default='Disponível', max_length=20, verbose_name='Status'),
        ),
    ]
