# Generated by Django 6.0.3 on 2026-05-27 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='operadores',
            field=models.ManyToManyField(blank=True, related_name='farms_operador', to=settings.AUTH_USER_MODEL, verbose_name='Operadores com Acesso'),
        ),
    ]
