# Generated by Django 6.0.3 on 2026-05-27 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_farm_operadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='operadores',
        ),
        migrations.AddField(
            model_name='user',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='api.farm', verbose_name='Fazenda Vinculada'),
        ),
    ]
