# Generated by Django 6.0.3 on 2026-05-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_user_farm_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.farm', verbose_name='Fazenda'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('operador', 'Operador'), ('visualizador', 'Visualizador')], default='visualizador', max_length=20, verbose_name='Tipo de Conta'),
        ),
    ]
