# Generated by Django 6.0.3 on 2026-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_farm_to_unidadearmazenadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='silo',
            name='tipo',
            field=models.CharField(choices=[('metalico', 'Metálico'), ('concreto', 'Concreto'), ('alvenaria', 'Alvenaria'), ('polietileno', 'Polietileno'), ('outro', 'Outro')], default='metalico', max_length=20, verbose_name='Tipo do Silo'),
        ),
    ]
