# Generated by Django 6.0.3 on 2026-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_silo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silo',
            name='tipo',
            field=models.CharField(choices=[('pulmao', 'Silo Pulmão'), ('armazenamento', 'Silo de Armazenamento')], default='pulmao', max_length=20, verbose_name='Tipo do Silo'),
        ),
    ]
