# Generated by Django 6.0.3 on 2026-06-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_silo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='motorista_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Motorista'),
        ),
        migrations.AddField(
            model_name='lote',
            name='placa_caminhao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa do Caminhão'),
        ),
    ]
