# Generated by Django 6.0.3 on 2026-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_lote_motorista_nome_lote_placa_caminhao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='peso_caminhao',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso do Caminhão (kg)'),
        ),
    ]
