# Generated by Django 6.0.3 on 2026-06-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_lote_peso_caminhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='tipo_processo',
            field=models.CharField(choices=[('Triagem', 'Triagem'), ('Secagem', 'Secagem'), ('Resfriamento', 'Resfriamento'), ('Armazenamento', 'Armazenamento')], default='Secagem', max_length=20, verbose_name='Tipo de Atividade'),
        ),
    ]
