# Generated by Django 6.0.3 on 2026-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_processo_tipo_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='dados_extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados Extras'),
        ),
    ]
