# Generated by Django 6.0.3 on 2026-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_processo_dados_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='secador',
            name='consumo_combustivel_hora',
            field=models.FloatField(blank=True, null=True, verbose_name='Consumo de Combustível (L/h ou kg/h)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='consumo_energia_kwh',
            field=models.FloatField(blank=True, null=True, verbose_name='Consumo de Energia (kWh)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='custo_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo de Aquisição (R$)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='custo_instalacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo de Instalação (R$)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='custo_manutencao_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo de Manutenção Anual (R$)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='custo_mao_obra_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Mão de Obra (R$/h)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='preco_combustivel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço do Combustível (R$/un)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='preco_kwh',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Preço da Energia (R$/kWh)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='valor_residual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Residual (R$)'),
        ),
        migrations.AddField(
            model_name='secador',
            name='vida_util_anos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida Útil (anos)'),
        ),
    ]
