# Generated by Django 6.0.3 on 2026-06-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_secador_consumo_combustivel_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorAeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_id', models.CharField(max_length=50, unique=True, verbose_name='ID do Motor')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição/Localização')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('falha', 'Falha'), ('desativado', 'Desativado')], default='ativo', max_length=20, verbose_name='Status Operacional')),
                ('estado', models.CharField(choices=[('ligado', 'Ligado'), ('desligado', 'Desligado')], default='desligado', max_length=20, verbose_name='Estado')),
                ('potencia_kw', models.FloatField(blank=True, null=True, verbose_name='Potência (kW)')),
                ('rpm', models.FloatField(blank=True, null=True, verbose_name='RPM')),
                ('vazao_ar', models.FloatField(blank=True, null=True, verbose_name='Vazão de Ar (m³/h)')),
                ('horimetro', models.FloatField(blank=True, null=True, verbose_name='Horímetro (horas)')),
                ('consumo_atual_kw', models.FloatField(blank=True, null=True, verbose_name='Consumo Atual (kW)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('secador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motores_aeracao', to='api.secador', verbose_name='Secador Vinculado')),
                ('silo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motores_aeracao', to='api.silo', verbose_name='Silo Vinculado')),
                ('unidade_armazenadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motores_aeracao', to='api.unidadearmazenadora', verbose_name='Unidade Armazenadora')),
            ],
            options={
                'verbose_name': 'Motor de Aeração',
                'verbose_name_plural': 'Motores de Aeração',
                'ordering': ['motor_id'],
            },
        ),
    ]
