# Generated by Django 5.0.4 on 2024-06-01 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id_sensor_data', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=25)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id_silo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('identificacao', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='silo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.silo'),
        ),
        migrations.CreateModel(
            name='Controlador',
            fields=[
                ('id_controlador', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.silo')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.sensor')),
                ('silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.silo')),
            ],
        ),
        migrations.CreateModel(
            name='AeracaoSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(help_text='Volume do silo em m³', null=True)),
                ('temperatura_inicial', models.FloatField(help_text='Temperatura inicial em °C', null=True)),
                ('umidade_inicial', models.FloatField(help_text='Umidade relativa inicial em %', null=True)),
                ('temperatura_desejada', models.FloatField(help_text='Temperatura desejada em °C', null=True)),
                ('umidade_desejada', models.FloatField(help_text='Umidade relativa desejada em %', null=True)),
                ('taxa_fluxo_ar', models.FloatField(help_text='Taxa de fluxo de ar em m³/s', null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.silo')),
            ],
        ),
    ]
